version: '3.6'
services:
  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
    networks:
     - default
  api:
    image: valrai/trainix:latest
    depends_on:
      - database
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    networks:
      - default
networks:
    default:
        driver: "bridge"
volumes:
    db-data:
